import { motion } from 'framer-motion'
import './About.css'

const About = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  }

  const itemVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.6,
        ease: [0.22, 1, 0.36, 1],
      },
    },
  }

  return (
    <section id="about" className="about">
      <motion.div
        className="about-container"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.3 }}
        variants={containerVariants}
      >
        <h2 className="section-title">About Me</h2>
        
        <motion.div className="about-content" variants={itemVariants}>
          <div className="about-text">
            <p className="about-intro">
              I'm an AI engineer based in Boston, finishing my M.S. in Information Systems at Northeastern (May 2026).
              I build things end-to-end — from data pipelines and model training to deployment and observability.
              My work sits at the intersection of multi-agent systems, RAG, and production ML infrastructure.
            </p>

            <div className="about-details">
              <motion.div className="about-section" variants={itemVariants}>
                <h3>Multi-Agent Systems</h3>
                <p>
                  I've built three production-grade multi-agent systems: <strong>Foresight</strong> (12 LangGraph agents + 6 custom MCP servers for proactive financial intelligence), <strong>JobPilot</strong> (autonomous job application agent using GPT-4o Vision + Playwright for computer use), and <strong>APEX</strong> (research scientist agent with adversarial hypothesis debate over a Neo4j knowledge graph). All three use Anthropic's Model Context Protocol as the tool abstraction layer.
                </p>
              </motion.div>

              <motion.div className="about-section" variants={itemVariants}>
                <h3>Custom ML Models</h3>
                <p>
                  I train and deploy custom models when prompting isn't the right answer. <strong>SpendingCategoryBERT</strong> (fine-tuned BERT, 99.8% cheaper than Claude per transaction, HuggingFace) classifies bank transactions for Foresight. <strong>HypothesisValidityBERT</strong> (~98% F1, HuggingFace) serves as APEX's fast-pass hypothesis validator before escalating to Claude. Both were trained with synthetic datasets generated by LLMs and tracked with MLflow.
                </p>
              </motion.div>

              <motion.div className="about-section" variants={itemVariants}>
                <h3>Data & Knowledge Graphs</h3>
                <p>
                  I work across multiple database paradigms depending on the problem. <strong>APEX</strong> uses Neo4j + GDS for graph-based knowledge gap detection (780 concepts, 3984 relationships) paired with Weaviate for semantic retrieval. <strong>Foresight</strong> uses Neo4j for subscription pattern detection and Qdrant for financial document search. I've also built Kafka-based event pipelines for agent observability and arXiv ingestion systems at scale.
                </p>
              </motion.div>

              <motion.div className="about-section" variants={itemVariants}>
                <h3>Computer Vision & Multimodal AI</h3>
                <p>
                  Built a <strong>Movie Semantic Search</strong> system combining YOLOv8 (96% actor recognition across 18 actors), CLIP embeddings, and FAISS for semantic video retrieval. Integrated GPT-4o Vision into JobPilot for reading arbitrary ATS application forms — a Vision-first approach that handles any form without per-site custom code. Also used Claude Vision for receipt OCR in Foresight's expense pipeline.
                </p>
              </motion.div>

              <motion.div className="about-section" variants={itemVariants}>
                <h3>Production & Infrastructure</h3>
                <p>
                  I care about systems that actually run. Foresight deploys on <strong>AWS ECS Fargate</strong> with modular Terraform IaC (5 modules, dev + prod environments), GitHub Actions CI/CD, and a full observability stack (LangSmith + MLflow + CloudWatch). Interned at <strong>HPE Singapore</strong> deploying ML models on Azure Functions and Azure ML Studio — rated Very Good by the programme.
                </p>
              </motion.div>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </section>
  )
}

export default About
